spring:
  application:
    name: test
  ai:
    openai:
      chat:
        options:
          model: ai/gemma3
      api-key: dummy
      base-url: http://localhost:12434/engines
#    model:
#      chat: ollama
    ollama:
      chat:
        options:
          model: llama3.2:1b
    chat:
      client:
        enabled: false

#  ai:
#    model:
#      chat: ollama
#    ollama:
#      chat:
#        options:
#          model: llama3.2:1b
#  ai:
#    openai:
#          api-key: ${OPENAI_API_KEY}

logging:
  level:
    root: DEBUG